// action types
const actionTypes = {
  // AUTH
  USER_LOGOUT: "USER_LOGOUT",
  USER_LOGIN: "USER_LOGIN",
  
  // RECIPE
  INIT_RECIPES: "INIT_RECIPES",
  SET_RECIPES: "SET_RECIPES",
  DELETE_RECIPE: "DELETE_RECIPE",
  ADD_RECIPE: "ADD_RECIPE",
  OPEN_RECIPE: "OPEN_RECIPE",
  CLOSE_RECIPE: "CLOSE_RECIPE"
}

export default actionTypes;